version: "3.6"

services:
  app:
    image: webdevops/php-apache:alpine-php7
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./www:/app
    links:
      - "db"
      
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programacao_web
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./dump:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

